# Generated by Django 6.0.6 on 2026-07-04 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('income', models.FloatField(verbose_name='Income')),
                ('kidhome', models.IntegerField(verbose_name='Kidhome')),
                ('teenhome', models.IntegerField(verbose_name='Teenhome')),
                ('recency', models.IntegerField(verbose_name='Recency')),
                ('mnt_wines', models.FloatField(verbose_name='MntWines')),
                ('mnt_fruits', models.FloatField(verbose_name='MntFruits')),
                ('mnt_meat_products', models.FloatField(verbose_name='MntMeatProducts')),
                ('mnt_fish_products', models.FloatField(verbose_name='MntFishProducts')),
                ('mnt_sweet_products', models.FloatField(verbose_name='MntSweetProducts')),
                ('mnt_gold_prods', models.FloatField(verbose_name='MntGoldProds')),
                ('num_deals_purchases', models.IntegerField(verbose_name='NumDealsPurchases')),
                ('num_web_purchases', models.IntegerField(verbose_name='NumWebPurchases')),
                ('num_catalog_purchases', models.IntegerField(verbose_name='NumCatalogPurchases')),
                ('num_store_purchases', models.IntegerField(verbose_name='NumStorePurchases')),
                ('num_web_visits_month', models.IntegerField(verbose_name='NumWebVisitsMonth')),
                ('accepted_cmp3', models.IntegerField(verbose_name='AcceptedCmp3')),
                ('accepted_cmp4', models.IntegerField(verbose_name='AcceptedCmp4')),
                ('accepted_cmp5', models.IntegerField(verbose_name='AcceptedCmp5')),
                ('accepted_cmp1', models.IntegerField(verbose_name='AcceptedCmp1')),
                ('accepted_cmp2', models.IntegerField(verbose_name='AcceptedCmp2')),
                ('complain', models.IntegerField(verbose_name='Complain')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('education_encoded', models.FloatField(verbose_name='Education_Encoded')),
                ('marital_absurd', models.FloatField(verbose_name='Marital_Absurd')),
                ('marital_alone', models.FloatField(verbose_name='Marital_Alone')),
                ('marital_divorced', models.FloatField(verbose_name='Marital_Divorced')),
                ('marital_married', models.FloatField(verbose_name='Marital_Married')),
                ('marital_single', models.FloatField(verbose_name='Marital_Single')),
                ('marital_together', models.FloatField(verbose_name='Marital_Together')),
                ('marital_widow', models.FloatField(verbose_name='Marital_Widow')),
                ('marital_yolo', models.FloatField(verbose_name='Marital_YOLO')),
                ('prediction_response', models.IntegerField(blank=True, null=True, verbose_name='Response')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Confidence Score')),
            ],
        ),
    ]
